# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='motorstate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('busCurrent', models.FloatField()),
                ('busVoltage', models.FloatField()),
                ('vehicleVelocity', models.FloatField()),
                ('motorVelocity', models.FloatField()),
                ('phaseACurrent', models.FloatField()),
                ('phaseBCurrent', models.FloatField()),
                ('vectVoltReal', models.FloatField()),
                ('vectVoltImag', models.FloatField()),
                ('vectCurrReal', models.FloatField()),
                ('vectCurrImag', models.FloatField()),
                ('backEMFReal', models.FloatField()),
                ('backEMFImag', models.FloatField()),
                ('fifteenVsupply', models.FloatField()),
                ('onesixfiveVsupply', models.FloatField()),
                ('twofiveVsupply', models.FloatField()),
                ('onetwoVsupply', models.FloatField()),
                ('fanSpeed', models.FloatField()),
                ('fanDrive', models.FloatField()),
                ('heatSinkTemp', models.FloatField()),
                ('motorTemp', models.FloatField()),
                ('airInletTemp', models.FloatField()),
                ('processorTemp', models.FloatField()),
                ('airOutletTemp', models.FloatField()),
                ('capacitorTemp', models.FloatField()),
                ('DCBusAmpHours', models.FloatField()),
                ('Odometer', models.FloatField()),
            ],
        ),
    ]
