# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorstate',
            options={'managed': False},
        ),
    ]
