# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_auto_20160417_0942'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='motorstate',
            table='motorstate',
        ),
    ]
