# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0003_auto_20160417_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorstate',
            options={'get_latest_by': 'id', 'managed': False},
        ),
    ]
