# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2014-04-23 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0004_auto_20160417_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorstate',
            options={'get_latest_by': 'msg_id', 'managed': False},
        ),
    ]
